### ISSUE TITLE
Lambdulus does not perform eta-reduction

### ISSUE THREAD

**Issue by peckato1** [lambdulus/original-frontend#12]
**Describe the bug**
Lambdulus does not perform eta-reduction and it says for expressions like `(\x. A x)` that they are in normal form.

**To Reproduce**
https://lambdulus.github.io/#(%CE%BBx.%20a%20x)

**Expected behavior**
Lambdulus should perform eta-reduction and it should not say that `(\x. A x)` is in normal form.
This way it does not conform to the definition from BI(E)-PPA which may be confusing (also some students may argue that "lambdulus says it was in normal form..." ).

We should either redesign the definition in the course (thats for internal discussion) or we should change the lambdulus behaviour.

**Comment by Taskkill** [comment]
Solved in the New Frontend.

**Comment by Taskkill** [comment]
Reopening - Eta reduction breaks SDE.
For example `+ 1 2`.
`+` needs its arguments to be in the normal form, right now Core has only one way to signal `normality` and that is returning `None` reduction when asked for the next step.
I will probably need to implement more aware solution in the Core.
Some predicate like `isBetaNormal` or so.
Simply put - general normality as a deciding factor is not enough anymore - to know if the expression should be used as is or not.

**Comment by Taskkill** [comment]
Solved in the Holo frontend.
